### ISSUE TITLE
Hotios Discord server invite link expired

### ISSUE THREAD

**Issue by jonas740** [mrhotio/mrhotio#1]
The discord server invite link has expired it seems.

**Comment by mrhotio** [comment]
What link?

**Comment by mrhotio** [comment]
https://hotio.dev/discord seems to redirect to a working link....

**Comment by jonas740** [comment]
The discord invite link found on your website. When trying to use it, I get
the message that the invite link I no longer valid.

Den sön 5 mars 2023 17:39mrhotio ***@***.***> skrev:

**Comment by mrhotio** [comment]
You’re probably banned then…
