### ISSUE TITLE
Issues with NC on porkbun. 

### ISSUE THREAD

**Issue by porkbunsmrshotio** [mrhotio/mrhotio#2]
Think you might have issues with porkbun, nameservers configured totally wrong.

I am guessing you had issues in your youth.

But have you read the docs?

https://www.ncab.org.au/bullying-advice/bullying-for-parents/definition-of-bullying/

You could share that with your friend driz aswell.

It is amusing to see how much energy you spend on me on discord. Probably in your thoughts aswell. You thought I was gone from your discord? Well as said, I have resources and skills. 

But bad written docs on your repo is something you might want to look into. 

I looked through your domain and it appears to have flaws, you might want to correct thoose.

Within the boundaries of the law I have taken actions towards you and also driz. I just wanted to let you know about that. 

This is actually me writing but for the rest of the journey one of my assistants will take care of the rest. 

Have a nice day.

**Comment by mrhotio** [comment]
I honestly couldn't care less about a person so pathetic as you, nor about your meaningless actions within the boundaries of the law. You seem to be forgetting that: I DIDN'T DO ANYTHING WRONG...

**Comment by mrhotio** [comment]
```
Bullying is an ongoing and deliberate misuse of power in relationships through repeated verbal, physical and/or social behaviour that intends to cause physical, social and/or psychological harm. 
```

We don't have any kind of relationship, so what's your point? Please do tell your assistants to only contact my assistants directly, so I don't get bothered by this noice, ok? Thx

**Comment by Roxedus** [comment]
Assistant here, My working hours are every 29th February, all day.

**Comment by mrhotio** [comment]
Imagine thinking your alt accounts are assistants...lol

**Comment by drizuid** [comment]
> Assistant here, My working hours are every 29th February, all day.

Looking to hire an assistant, 1day/yr, non leap years. Payment is made in snark. Am very scared of Jonas' legal action against me 🙀
